name: Move assigned card to In Progress
on:
  issues:
    types: [ assigned ]
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: kin/gh-action-move-issue-to-column@1.0
        with:
          project-name: ITU-BDSA2024-GROUP20 Chirp
          target-column: In Progress
          access-token: ${{ secrets.GITHUB_TOKEN }}
