name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move assigned to In Progress
        uses: fojia/action-move-issues-to-column@master
        with:
          project: 'ITU-BDSA2024-GROUP20 Chirp'
          column: 'In Progress'
          repo: Chirp
          github_token: ${{ secrets.GITHUB_TOKEN }}
