# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

run-name: Upload of ${{ github.ref_name }} by @${{ github.actor }}
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restoring Projects
        run: |
          dotnet restore ./src/Chirp.Web
          dotnet restore ./test/Chirp.Razor.Test
          dotnet restore ./test/Chirp.Web.Test
      - name: Building Projects
        run: |
          dotnet build ./src/Chirp.Web --no-restore
          dotnet build ./test/Chirp.Razor.Test --no-restore
          dotnet build ./test/Chirp.Web.Test --no-restore
      - name: Testing Projects
        run: |
          dotnet test --no-build --verbosity normal "./test/Chirp.Web.Test"
          dotnet test --no-build --verbosity normal "./test/Chirp.Razor.Test"
      - name: Publish as Artifacts
        run: |
          dotnet publish ./src/Chirp.Web -c Release -r linux-x64 -o ./artifact/linux
          dotnet publish ./src/Chirp.Web -c Release -r win-x64 -o ./artifact/win
          dotnet publish ./src/Chirp.Web -c Release -r osx-x64 -o ./artifact/mac
      - name: Zip Artifacts
        run: |
          zip -r Chirp-Win.zip ./artifact/win
          zip -r Chirp-Linux.zip ./artifact/linux
          zip -r Chirp-Mac.zip ./artifact/mac
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ github.ref_name }}
          files: |
            Chirp-Win.zip
            Chirp-Linux.zip
            Chirp-Mac.zip