# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies for Chirp.CLI
      run: dotnet restore "${{ github.workspace }}/src/Chirp.CLI"
    - name: Restore dependencies for SimpleDB
      run: dotnet restore "${{ github.workspace }}/src/SimpleDB"
    - name: Build Chirp.CLI
      run: dotnet build --no-restore "${{ github.workspace }}/src/Chirp.CLI"
    - name: Build SimpleDB
      run: dotnet build --no-restore "${{ github.workspace }}/src/SimpleDB"
    - name: Test Chirp.CLI
      run: dotnet test --no-build --verbosity normal "${{ github.workspace }}/test/Chirp.CLI.Test"
    - name: Test SimpleDB
      run: dotnet test --no-build --verbosity normal "${{ github.workspace }}/test/SimpleDB.Test"
