# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

run-name: Upload of ${{ github.ref_name }} by @${{ github.actor }}
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restoring Projects
        run: |
          dotnet restore ./src/Chirp.CLI
          dotnet restore ./test/Chirp.CLI.Test
          dotnet restore ./src/SimpleDB
          dotnet restore ./test/SimpleDB.Test
      - name: Building Projects
        run: |
          dotnet build ./src/Chirp.CLI --no-restore
          dotnet build ./test/Chirp.CLI.Test --no-restore
          dotnet build ./src/SimpleDB --no-restore
          dotnet build ./test/SimpleDB.Test --no-restore
      - name: Testing Projects
        run: |
          dotnet test --no-build --verbosity normal "./test/Chirp.CLI.Test"
          dotnet test --no-build --verbosity normal "./test/SimpleDB.Test"
      - name: Publish
        run: |
          dotnet publish ./src/Chirp.CLI -c Release -r linux-x64
          dotnet publish ./src/Chirp.CLI -c Release -r win-x64
          dotnet publish ./src/Chirp.CLI -c Release -r osx-x64
      - name: Zip Project
        run: |
          zip -r Chirp-Win.zip ./src/Chirp.CLI/obj/Release/net7.0/win-x64
          zip -r Chirp-Linux.zip ./src/Chirp.CLI/obj/Release/net7.0/linux-x64
          zip -r Chirp-Mac.zip ./src/Chirp.CLI/obj/Release/net7.0/osx-x64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ github.ref_name }}
          files: |
            Chirp-Win.zip
            Chirp-Linux.zip
            Chirp-Mac.zip