# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  [ create ]

jobs:
  build:
    strategy:
        matrix:
          kind: [ 'Chirp.CLI' , 'SimpleDB' ]
          target: [ linux-x64 , win-x64 , osx-x64 ]
          os: [ ubuntu-latest , windows-latest , macos-latest ]
          include:
            - target: linux-x64
              os: ubuntu-latest
            - target: win-x6
              os: windows-latest
            - target: osx-x64
              os: macos-latest
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - run: echo "Restoring Dependencies..."
    - name: Restore dependencies for ${{ matrix.kind }}
      run: dotnet restore "${{ github.workspace }}/src/${{ matrix.kind }}"
    - name: Restore dependencies for ${{ matrix.kind }}.Test
      run: dotnet restore "${{ github.workspace }}/test/${{ matrix.kind }}.Test"
    - run: echo "Restored Dependencies!"
    
    - run: echo "Building Projects..."
    - name: Build ${{ matrix.kind }}
      run: dotnet build --no-restore "${{ github.workspace }}/src/${{ matrix.kind }}"
    - name: Build ${{ matrix.kind }}.Test
      run: dotnet build --no-restore "${{ github.workspace }}/test/${{ matrix.kind }}.Test"
    - run: echo "Build the Projects!"
    
    - run: echo "Testing Projects..."
    - name: Test ${{ matrix.kind }}.Test
      run: dotnet test --no-build --verbosity normal "${{ github.workspace }}/test/${{ matrix.kind }}.Test"
    - run: echo "Testing Complete!"

    - run: echo "Packaging Project"
    - name: Package
      run: dotnet pack --configuration Release ${{ matrix.kind }}
