# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  [ create ]

jobs:
  build:
    strategy:
        matrix:
          project: [ 'Chirp.CLI' , 'SimpleDB' ]
          kind: [ 'linux' , 'windows' , 'mac' ]
          include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - run: echo "Restoring Dependencies..."
    - name: Restore dependencies for ${{ matrix.project }}
      run: dotnet restore "${{ github.workspace }}/src/${{ matrix.project }}"
    - name: Restore dependencies for ${{ matrix.project }}.Test
      run: dotnet restore "${{ github.workspace }}/test/${{ matrix.project }}.Test"
    - run: echo "Restored Dependencies!"
    
    - run: echo "Building Projects..."
    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore "${{ github.workspace }}/src/${{ matrix.project }}"
    - name: Build ${{ matrix.project }}.Test
      run: dotnet build --no-restore "${{ github.workspace }}/test/${{ matrix.project }}.Test"
    - run: echo "Build the Projects!"
    
    - run: echo "Testing Projects..."
    - name: Test ${{ matrix.project }}.Test
      run: dotnet test --no-build --verbosity normal "${{ github.workspace }}/test/${{ matrix.project }}.Test"
    - run: echo "Testing Complete!"

    - run: echo "Packaging Project"
    - name: Package
      run: dotnet pack --configuration Release ${{ matrix.project }}
