# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  [ create ]

jobs:
  build:
    strategy:
        matrix:
          project: [ 'Chirp.CLI' , 'SimpleDB' ]
          os: [ ubuntu-latest , windows-latest , macos-latest ] 
          include:
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: win-x64
          - os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies for ${{ matrix.project }}
      run: dotnet restore "${{ github.workspace }}/src/${{ matrix.project }}"
    - name: Restore dependencies for ${{ matrix.project }}.Test
      run: dotnet restore "${{ github.workspace }}/test/${{ matrix.project }}.Test"
    
    - name: Build ${{ matrix.project }}
      run: dotnet build --no-restore "${{ github.workspace }}/src/${{ matrix.project }}"
    - name: Build ${{ matrix.project }}.Test
      run: dotnet build --no-restore "${{ github.workspace }}/test/${{ matrix.project }}.Test"

    - name: Publishing ${{ matrix.project }}
      run: dotnet publish "${{ github.workspace }/src/Chirp.CLI/Chirp.CLI.csproj" -c Release -r ${{ matrix.target }}
    
    - name: Test ${{ matrix.project }}.Test
      run: dotnet test --no-build --verbosity normal "${{ github.workspace }}/test/${{ matrix.project }}.Test"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "App*"
